vich_uploader:
    db_driver: orm

   # mappings:
    #    products:
     #      uri_prefix: %product_attachement%
    #     upload_destination: '%kernel.project_dir%/public/%product_attachement%'
     #      namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
   